#!/bin/sh -ef

install -Dm755 rc.conf     "$1/etc/rc.conf"
install -Dm755 mine.boot   "$1/etc/rc.d/mine.boot"
install -Dm755 rc.lib      "$1/lib/init/rc.lib"
install -Dm755 rc.boot     "$1/lib/init/rc.boot"
install -Dm755 rc.shutdown "$1/lib/init/rc.shutdown"

mkdir -p "$1/usr/bin"
for bin in kpow.c kall.c; do
    "${CC:-cc}" -o "$1/usr/bin/${bin%.c}" "$bin" $CFLAGS -static
done
