#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr/local

make

for f in free pgrep pkill pmap pwdx slabtop sysctl tload vmstat w watch ; do
    install -D "$f" "$1/usr/local/bin/$f"
done

install -D ps/pscommand "$1/usr/local/bin/ps"
install -D top/top "$1/usr/local/bin/top"
