#!/bin/sh -e

wget https://dl.suckless.org/sinit/sinit-1.0.tar.gz
echo "78c2120a97a5e93b80606c5403bd731152f8a344e47aa4ab74970c1c11dc6fc0" sinit-1.0.tar.gz | sha256sum -c -
tar zxvf sinit-1.0.tar.gz
cat << EOF > sinit-1.0/config.h
static char *const rcinitcmd[]     = { "/boot/dash2el.sh", NULL };
static char *const rcrebootcmd[]   = { "/lib/init/rc.shutdown", "reboot", NULL };
static char *const rcpoweroffcmd[] = { "/lib/init/rc.shutdown", "poweroff", NULL };
EOF
cd sinit-1.0
make CFLAGS="$CFLAGS -static"
install -Dm 755 sinit "$1/boot/sinit"
cd ..

install -Dm 755 boot.el "$1/boot/boot.el"

./configure \
    --prefix=/boot/emacs \
    --with-modules \
    --without-all \
    --without-x \
    --with-x-toolkit=no \
    --with-x=no

make
make DESTDIR="$1" install
