#!/bin/sh -e

export CFLAGS="$CFLAGS -Wno-error -static"

./configure \
    --prefix=/usr/local

make
make DESTDIR="$1" install

ln -s "$1/usr/local/bin/grep" "$1/usr/local/bin/ggrep" # for kiss pkg manager
