#!/bin/sh -e

touch autopoint && chmod +x autopoint
PATH=$PWD:$PATH

for patch in *.patch; do /usr/local/bin/patch -p1 < "$patch"; done

./autogen.sh

LIBS="-lintl" ./configure \
    --prefix=/usr \
    --disable-nls

make
make DESTDIR="$1" install
