#!/bin/sh -e

python ./configure.py \
       --shared-zlib \
       --without-intl \
       --without-etw \
       --without-dtrace \
       --without-report \
       --without-node-snapshot \
       --without-node-code-cache

make
make DESTDIR="$1" install

# Remove unneeded headers.
rm -rf "$1/usr/include/node/openssl"
