#!/bin/sh -e

#for patch in *.diff; do /opt/gnu/patch/bin/patch -p1 < "$patch"; done

# install POST-patching defconfig to /etc/ incase mine.config.def.h causes build fail
install -Dm 755 config.def.h "$1/etc/kiss/defconfig/dwm"

mv mine.config.def.h config.def.h

make CFLAGS="$CFLAGS -static" X11INC=/usr/include/X11 X11LIB=/usr/lib FREETYPEINC=/usr/include/freetype2 PREFIX=/usr DESTDIR="$1" install
